version: '3'
services:
  ganache:
    image: 'trufflesuite/ganache-cli'
    ports:
      - '8545:8545'
    networks:
      - domimi
  remix:
    image: 'remixproject/remix-ide'
    ports:
      - '8080:80'
  domimi-server:
    image: 'node:14-alpine'
    volumes:
      - './server:/app'
    working_dir: '/app'
    command: 'node main.js'
    ports:
      - '3000:3000'
    networks:
      - domimi
  domimi-client:
    image: 'nginx:alpine'
    volumes:
      - './client:/usr/share/nginx/html:ro'
    ports:
      - '8000:80'
networks:
  domimi:
